# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-08 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rom',
            old_name='furniture',
            new_name='furnitures',
        ),
    ]
